# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    perro.form.registration:
        class: Sistema\PerroUserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: perro_user_registration }
