<?php

namespace Sistema\PerroEncontradoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PerroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerroRepository extends EntityRepository
{
}
